/*
569. Median Employee Salary

https://leetcode.com/problems/median-employee-salary/


CREATE TABLE EMPLOYEE (
id number(4),
company varchar2(4),
salary number(6)
);

INSERT INTO EMPLOYEE VALUES (1,'A',2341);
INSERT INTO EMPLOYEE VALUES (2,'A',341);
INSERT INTO EMPLOYEE VALUES (3,'A',15);
INSERT INTO EMPLOYEE VALUES (4,'A',15314);
INSERT INTO EMPLOYEE VALUES (5,'A',451);
INSERT INTO EMPLOYEE VALUES (6,'A',513);
INSERT INTO EMPLOYEE VALUES (7,'B',15);
INSERT INTO EMPLOYEE VALUES (8,'B',13);
INSERT INTO EMPLOYEE VALUES (9,'B',1154);
INSERT INTO EMPLOYEE VALUES (10,'B',1345);
INSERT INTO EMPLOYEE VALUES (11,'B',1221);
INSERT INTO EMPLOYEE VALUES (12,'B',234);
INSERT INTO EMPLOYEE VALUES (13,'C',2345);
INSERT INTO EMPLOYEE VALUES (14,'C',2645);
INSERT INTO EMPLOYEE VALUES (15,'C',2645);
INSERT INTO EMPLOYEE VALUES (16,'C',2652);
INSERT INTO EMPLOYEE VALUES (17,'C',65);



*/






